version: "3.5"

services:
  echo-server-service:
    build: .
#    image: echo-server:v1
    container_name: echo-server-service
    restart: always
#    volumes:
#      - ./echo-server:/app/server:ro
    ports:
      - 1323:1323
    networks:
      - echo-network
    links:
      - mongo-server-echo

  mongo-server-echo:
    image: mongo
    container_name: mongo-server-echo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
#      - ./mongodb/data:/data/db
    command: mongod --auth
    networks:
      - echo-network

networks:
  echo-network:
    name: echo-network