apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes 2;
    pid /var/run/nginx.pid;

    events {
            worker_connections 1024;
            # multi_accept on;
    }

    http {

            ##
            # Basic Settings
            ##

            server_tokens off;

            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            keepalive_timeout 65;
            types_hash_max_size 2048;
            # server_tokens off;

            # server_names_hash_bucket_size 64;
            # server_name_in_redirect off;

            include /etc/nginx/mime.types;
            default_type application/octet-stream;

            ##
            # Logging Settings
            ##

            access_log /var/log/nginx/access.log;
            error_log /var/log/nginx/error.log;

            ##
            # Gzip Settings
            ##

            gzip  on;
            gzip_http_version 1.1;
            gzip_vary on;
            gzip_comp_level 6;
            gzip_proxied any;
            gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript text/x-js;
            gzip_buffers 16 8k;
            gzip_disable "msie6";


            ##
            # Virtual Host Configs
            ##

            include /etc/nginx/conf.d/*.conf;
            include /etc/nginx/default.d/*;

            server {
                    listen 80 default_server;
                    listen [::]:80 default_server;
                    server_name _;

                    #listen       80;
                    #server_name  localhost;

                    #charset koi8-r;

                    #access_log  logs/host.access.log  main;

                    location / {
                        root /usr/share/nginx/html;
                        index index.html index.htm;
                    }

                    location /api/ {
                        rewrite /api/(.*) /$1  break;
                        proxy_pass http://echo-server:1323;
                    }

                    #error_page  404              /404.html;

                    # redirect server error pages to the static page /50x.html
                    #
                    error_page   500 502 503 504  /50x.html;
                    location = /50x.html {
                        root dist;
                    }

                    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
                    #
                    #location ~ \.php$ {
                    #    proxy_pass   http://127.0.0.1;
                    #}

                    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
                    #
                    #location ~ \.php$ {
                    #    root           html;
                    #    fastcgi_pass   127.0.0.1:9000;
                    #    fastcgi_index  index.php;
                    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
                    #    include        fastcgi_params;
                    #}

                    # deny access to .htaccess files, if Apache's document root
                    # concurs with nginx's one
                    #
                    #location ~ /\.ht {
                    #    deny  all;
                    #}
            }

    }