---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  ports:
    - name: echo-server
      protocol: TCP
      port: 1323
      targetPort: 1323
  selector:
    app: echo-server
    tier: echo-server
  type: LoadBalancer

---
apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
      tier: echo-server
      track: stable
  template:
    metadata:
      labels:
        app: echo-server
        tier: echo-server
        track: stable
    spec:
      containers:
        - name: echo-server
#          image: echo-server:local_v1
          image: echo-server:u_auth_v1
          ports:
            - containerPort: 1323
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: echo-data
              mountPath: /k8s/echo
              readOnly: true
      volumes:
        - name: echo-data
          persistentVolumeClaim:
            claimName: echo-store

