---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
  #    - port: 443
  #      protocol: TCP
  #      targetPort: 27017
  #      name: https
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          ports:
            - name: nginx
              containerPort: 80
          volumeMounts:
            - name: nginx-storage
              mountPath: /var/log/nginx
            - name: nginx-html-storage
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
#              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: nginx-pv-logs-storage
        - name: nginx-html-storage
          persistentVolumeClaim:
            claimName: nginx-pv-html-storage