---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv-logs-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/nginx/logs"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv-html-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/nginx/html"