---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  ports:
    - name: echo-server
      port: 1323
      targetPort: 1323
  selector:
    app: echo-server
  type: LoadBalancer

---
apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
#          image: echo-server:local_v1
          image: echo-server:u_auth_v1
          ports:
            - containerPort: 1323
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: echo-data
              mountPath: /k8s/echo
              readOnly: true
      volumes:
        - name: echo-data
          persistentVolumeClaim:
            claimName: echo-store

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
