---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pv-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi