---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      protocol: TCP
#    - port: 443
#      protocol: TCP
#      targetPort: 27017
#      name: https
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        environment: test
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: nginx
              containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          volumeMounts:
            - name: nginx-logs-data
              mountPath: /var/log/nginx
      volumes:
        - name: nginx-logs-data
          persistentVolumeClaim:
            claimName: nginx-pv-logs-storage